services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"

  pet-profile-service:
    build: ./pet-profile-service
    ports:
      - "3002:3002"

  appointment-service:
    build: ./appointment-service
    ports:
      - "3003:3003"

  notification-service:
    build: ./notification-service
    ports:
      - "3004:3004"