apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: petpal
data:
  MONGO_URI_USERS: "mongodb+srv://acsujan69:petpal123@petpal.9k6d9qu.mongodb.net/petpal_users"
  MONGO_URI_PETS: "mongodb+srv://acsujan69:petpal123@petpal.9k6d9qu.mongodb.net/petpal_pets"
  MONGO_URI_APPOINTMENTS: "mongodb+srv://acsujan69:petpal123@petpal.9k6d9qu.mongodb.net/petpal_appointments"
  MONGO_URI_MEDICAL: "mongodb+srv://acsujan69:petpal123@petpal.9k6d9qu.mongodb.net/petpal_medical"