apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-service
  namespace: petpal
  labels:
    app: pet-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pet-service
  template:
    metadata:
      labels:
        app: pet-service
    spec:
      containers:
      - name: pet-service
        image: petpal/pet-service:latest
        ports:
        - containerPort: 5002
        env:
        - name: MONGODB_URI
          value: "mongodb+srv://acsujan69:petpal123@petpal.9k6d9qu.mongodb.net/"
        - name: DATABASE_NAME
          value: "petpal_pets"
        - name: USER_SERVICE_URL
          value: "http://user-service:5001"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: pet-service
  namespace: petpal
  labels:
    app: pet-service
spec:
  selector:
    app: pet-service
  ports:
  - port: 5002
    targetPort: 5002
    protocol: TCP
  type: ClusterIP