apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: petpal
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
          name: web
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
        - name: prometheus-storage
          mountPath: /prometheus
        args:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
        - '--web.enable-lifecycle'
        - '--storage.tsdb.retention.time=30d'
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
      - name: prometheus-storage
        persistentVolumeClaim:
          claimName: prometheus-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: petpal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard-rwo

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: petpal
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']
    
    - job_name: 'user-service'
      static_configs:
      - targets: ['user-service:5001']
      metrics_path: '/metrics'
      scrape_interval: 30s
    
    - job_name: 'pet-service'
      static_configs:
      - targets: ['pet-service:5002']
      metrics_path: '/metrics'
      scrape_interval: 30s
    
    - job_name: 'appointment-service'
      static_configs:
      - targets: ['appointment-service:5003']
      metrics_path: '/metrics'
      scrape_interval: 30s
    
    - job_name: 'medical-service'
      static_configs:
      - targets: ['medical-service:5004']
      metrics_path: '/metrics'
      scrape_interval: 30s
    
    - job_name: 'frontend'
      static_configs:
      - targets: ['frontend:5000']
      metrics_path: '/metrics'
      scrape_interval: 30s

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: petpal
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: web
  type: LoadBalancer