apiVersion: v1
kind: Secret
metadata:
  name: petpal-secrets
  namespace: petpal
type: Opaque
data:
  # Base64 encoded values
  # mongodb+srv://acsujan69:petpal123@petpal.9k6d9qu.mongodb.net/petpal
  mongo-uri: bW9uZ29kYitzcnY6Ly9hY3N1amFuNjk6cGV0cGFsMTIzQHBldHBhbC45azZkOXF1Lm1vbmdvZGIubmV0L3BldHBhbA==
  # petpal-secret-key-2024
  secret-key: cGV0cGFsLXNlY3JldC1rZXktMjAyNA==