apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: petpal
  labels:
    app: user-service
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        version: v1
    spec:
      containers:
      - name: user-service
        image: gcr.io/petpal-467223/user-service:latest
        ports:
        - containerPort: 5001
          name: http
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: petpal-secrets
              key: mongo-uri
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: petpal-secrets
              key: secret-key
        - name: PORT
          value: "5001"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: petpal
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
    name: http
  type: ClusterIP
