runtime: python39

service: medical-service
instance_class: F2

env_variables:
  MONGO_URI: "mongodb+srv://acsujan69:petpal123@petpal.9k6d9qu.mongodb.net/petpal"
  SECRET_KEY: "petpal-secret-key-2024"

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.7